### ISSUE TITLE
Somalian App crashing on assess module

### ISSUE THREAD

**Issue by ifoche** [ifoche/malariapp#2348] opened 2019-09-13 07:43 UTC
Report from tester:

The Somaliland is finding some issues with the app. It is very weird but if we start a survey for from the Plan module the app works well but if I try the same survey and facility from the Assess module, the app crashes. I reviewed the users settings and the orgunits and I found everything well. Can you kindly help troubleshoot? These are the details:

- Server: https://sm-dev.hnqis.org
- User Credentials: in Slack
- App version 1.4.2

**Comment by xurxodev** [comment] 2019-09-13 10:11
The problem is the Org units in our database are not assigned to an org unit level.

The downloaded org units in the app are:
https://sm-dev.hnqis.org/api/organizationUnits/UVsWsU6MWJQ
https://sm-dev.hnqis.org/api/organizationUnits/lBul4KtUSbH
https://sm-dev.hnqis.org/api/organizationUnits/rHeWgOGqWwV
https://sm-dev.hnqis.org/api/organizationUnits/QYd0dIk9W8i
https://sm-dev.hnqis.org/api/organizationUnits/wlckuIlWLTH
https://sm-dev.hnqis.org/api/organizationUnits/cZfuhIqzIpe
https://sm-dev.hnqis.org/api/organizationUnits/obWFZbhVTxR

All org units are assigned to level 6 and on this request, you can see that there are 5 levels
https://sm-dev.hnqis.org/api/organizationUnitLevels

Our pull process under these circumstances assign orgUnitLevel = null

And this is a problem to create surveys from CreateSurveyFragment

**Closed as completed** 2019-09-14 09:56 UTC
Labels: HNQIS, priority - high, type - maintenance
